version: '3.8'
services:
  mongo:
    image: ${MONGO_IMAGE}
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  backend:
    image: ${BACKEND_IMAGE}              
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL= ${MONGO_URL}
    depends_on:
      - mongo
    networks:  
      - app_network

  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
