version: '3.8'
services:
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  backend:
    image: leelavahi137/backend:latest              
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo/myapp
    depends_on:
      - mongo
    networks:
      - app_network

  frontend:
    image: leelavahi137/frontend:latest
    container_name: frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
