apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: leelavahi137/frontend:latest
        ports:
        - containerPort: 4000
        env:
        - name: REACT_APP_API_URL          # React apps use env variables prefixed with REACT_APP_
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap    # Name of your ConfigMap
              key: REACT_APP_API_URL

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
